server:
  port: 9999

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
#      password:

  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
          username: root
          password: root

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: net.mall.user.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 到控制台

url: http://localhost:9999